services:
  postgres_db:
    image: postgres:16
    container_name: postgres_db

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5435:5432"

    volumes:
      - postgres_agents_data:/var/lib/postgresql/data

volumes:
  postgres_agents_data: